version: '2.1'
services:

  elasticsearch1:
    build: ./elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    links:
      - smtp-service
    networks:
      elk-network:
        ipv4_address: 172.16.238.10
        ipv6_address: 2001:3984:3989::10
    volumes:
      - es1-data:/usr/share/elasticsearch/data
      - es1-logs:/usr/share/elasticsearch/logs
      - es1-plugins:/usr/share/elasticsearch/plugins
      - es1-scripts:/usr/share/elasticsearch/scripts
    command: elasticsearch -Des.network.host=0.0.0.0

  elasticsearch2:
    build: ./elasticsearch
    ports:
      - "8200:9200"
      - "8300:9300"
    links:
      - smtp-service
    networks:
      elk-network:
        ipv4_address: 172.16.238.20
        ipv6_address: 2001:3984:3989::20
    volumes:
      - es2-data:/usr/share/elasticsearch/data
      - es2-logs:/usr/share/elasticsearch/logs
      - es2-plugins:/usr/share/elasticsearch/plugins
      - es2-scripts:/usr/share/elasticsearch/scripts
    command: elasticsearch -Des.network.host=0.0.0.0

  kopf:
    image: lmenezes/elasticsearch-kopf
    networks:
      elk-network:
        ipv4_address: 172.16.238.30
        ipv6_address: 2001:3984:3989::30
    ports:
      - 8080:80
    environment:
      - KOPF_SERVER_NAME=dockerhost
      - KOPF_ES_SERVERS=172.16.238.10:9200

  kibana:
    depends_on:
      elasticsearch1:
        condition: service_healthy
      elasticsearch2:
        condition: service_healthy
    build: ./kibana
    ports:
      - "5601:5601"
    links:
      - elasticsearch1
    networks:
      elk-network:
        ipv4_address: 172.16.238.40
        ipv6_address: 2001:3984:3989::40
    environment:
      - ELASTICSEARCH_URL=http://172.16.238.10:9200

  logstash:
    depends_on:
      elasticsearch1:
        condition: service_healthy
      elasticsearch2:
        condition: service_healthy
    build: ./logstash
    links:
      - elasticsearch1
      - elasticsearch2
    networks:
      elk-network:
        ipv4_address: 172.16.238.50
        ipv6_address: 2001:3984:3989::50

  license-call1:
    depends_on:
      elasticsearch1:
        condition: service_healthy
    build: ./license-call
    links:
      - elasticsearch1
    networks:
      elk-network:
        ipv4_address: 172.16.238.60
        ipv6_address: 2001:3984:3989::60
    command: http://172.16.238.10:9200/_license

  license-call2:
    depends_on:
      elasticsearch2:
        condition: service_healthy
    build: ./license-call
    links:
      - elasticsearch2
    networks:
      elk-network:
        ipv4_address: 172.16.238.70
        ipv6_address: 2001:3984:3989::70
    command: http://172.16.238.20:9200/_license

  smtp-service:
    image: namshi/smtp
    networks:
      elk-network:
        ipv4_address: 172.16.238.80
        ipv6_address: 2001:3984:3989::80
    ports:
      - "8025:25"

volumes:
  # elasticsearch 1
  es1-data:
  es1-logs:
  es1-plugins:
  es1-scripts:
  # elasticsearch 2
  es2-data:
  es2-logs:
  es2-plugins:
  es2-scripts:

networks:
  elk-network:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "true"
    ipam:
      driver: default
      config:
      - subnet: 172.16.238.0/24
        gateway: 172.16.238.1
      - subnet: 2001:3984:3989::/64
        gateway: 2001:3984:3989::1
